### ISSUE TITLE
Example of params.json file

### ISSUE THREAD

**Issue by LeonhardEulerr** [mightbxg/DistortImage#2]
Hello @mightbxg, thanks for nice and clean code for distorting the images.

I am just windering if distortion params from params.json are in the same form as in Brown-Conrady distortion model (k_1, k_2,...)?

I would really appreciate if you showed how the params.json looks :)

Thanks!

**Comment by mightbxg** [comment]
Just build and run [calibrate](https://github.com/mightbxg/DistortImage/blob/42477f4d5061cc04d145608bc33ad7c9f350982b/CMakeLists.txt#L8), it will output `params.json`. The [images](https://github.com/mightbxg/DistortImage/tree/master/images) for calibration are from the OpenCV repository.
